FROM alpine@sha256:e1c082e3d3c45cccac829840a25941e679c25d438cc8412c2fa221cf1a824e6a

RUN apk update && apk add --no-cache bash wget ca-certificates gnupg

# Add GNU Lib C
ENV GLIBC_VERSION=2.34-r0
RUN wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub && \
  wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-${GLIBC_VERSION}.apk && \
  wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-bin-${GLIBC_VERSION}.apk

RUN apk update && \
  apk --no-cache add glibc-${GLIBC_VERSION}.apk && \
	apk --no-cache add glibc-bin-${GLIBC_VERSION}.apk && \
  rm -f glibc-*

COPY ./elements/bin /usr/local/bin/
COPY ./elements/include /usr/local/include/
COPY ./elements/lib /usr/local/lib/
COPY ./elements/share /usr/local/share/
