FROM ubuntu@sha256:d26d529daa4d8567167181d9d569f2a85da3c5ecaf539cace2c6223355d69981 AS builder

ENV BITCOIN_VERSION=v0.18.0

RUN apt-get update  && apt-get upgrade -yq && \
  apt-get install -qfy git curl build-essential libtool autotools-dev automake pkg-config bsdmainutils python3
  
RUN git clone https://github.com/bitcoin/bitcoin /opt/bitcoin && \
  cd /opt/bitcoin && \
  git checkout ${BITCOIN_VERSION} && \
  ./autogen.sh && \
  cd depends && make NO_QT=1 HOST=x86_64-linux-gnu && \
  cd /opt/bitcoin && \
  ./configure --without-gui --prefix=/opt/bitcoin/depends/x86_64-linux-gnu --disable-bench --disable-tests && \
  make && make install

FROM alpine@sha256:28ef97b8686a0b5399129e9b763d5b7e5ff03576aa5580d6f4182a49c5fe1913

RUN apk update && apk add --no-cache bash wget ca-certificates gnupg

# Add GNU Lib C
ENV GLIBC_VERSION=2.28-r0
RUN wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub && \
  wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-${GLIBC_VERSION}.apk && \
  wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-bin-${GLIBC_VERSION}.apk

RUN apk update && \
  apk --no-cache add glibc-${GLIBC_VERSION}.apk && \
	apk --no-cache add glibc-bin-${GLIBC_VERSION}.apk && \
  rm -f glibc-*

COPY --from=builder /opt/bitcoin/x86_64-linux-gnu/bin/* /usr/local/bin/
