FROM debian:bookworm-slim

# Packages a Bitcoin Core tree produced by ./run-guix.sh.

RUN apt-get update \
  && apt-get install -qfy --no-install-recommends ca-certificates \
  && rm -rf /var/lib/apt/lists/*

COPY ./bitcoin/ /usr/local/
